baseURL:https://vaniduggal22.netlify.app/
languageCode: en-us
title: Portfolio Website for Vani
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: Portfolio Website
    
    title: Hi, my name is Vani
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: Liverpool Street
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: vduggal.mam2023@london.edu
    enable: yes
    phone:
      - phone: (+44) 7783453874 
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Vani
    enable: yes
    quicklinks:
      #- alt: HTML5 UP
       # text: 'Design: '
        #url: https://www.html5up.net
    social:
      #- icon: fa-twitter
       # label: Twitter
        #url: https://www.twitter.com/kostisc
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/vani.duggal.3
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/vaniiduggal/
      - icon: fa-github
        label: GitHub
        url: https://github.com/vaniduggal22
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/vani-duggal/
  image: ''
  name: Vani
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
     # - name: Generic Blog
      #  url: blogs/ipsum
      #- name: Elements
        #url: elements.html
    menu: Menu
    #subtitle: By HTML5 Up
    title: Vani's Portfolio
  tiles:
    enable: yes
    showcase:
      - image: me.jpeg
        subtitle: Hii, this is Vani!
        title: About me
        url: blogs/aliquam
      - image: energy.jpeg
        subtitle: Renewable Energy
        title: Renewable Energy Analysis
        url: blogs/tempus
      - image: sanfr.jpeg
        subtitle: Lorem Etiam Nullam
        title: San Francisco Rent Analysis
        url: blogs/magna
      - image: youth.jpeg
        subtitle: Nisl Sed Aliquam
        title: Youth Risk Behavior Analysis
        url: blogs/ipsum
      - image: climate.jpeg
        subtitle: Ipsum Dolor Sit Amet
        title: Climate change and temperature
        url: blogs/consequat
      - image: resume.jpeg
        #subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/etiam
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
